### ISSUE TITLE
Receiving `httpx.ReadTimeout` when using the API

### ISSUE THREAD

**Issue by rmanaem** [neurobagel/api#102]

**Comment by surchs** [comment]
Can you reproduce this by running the API locally with some example data?

**Comment by rmanaem** [comment]
I'm not quite sure, this produced when we were making changes to graph and tools for the recent demo.

**Comment by surchs** [comment]
Can you please confirm this is reproducible, it is currently a blocking issue

**Comment by rmanaem** [comment]
Closing this as it is no longer there.
