### ISSUE TITLE
[FIX] Avoid using shell variable names that are likely to clash

### ISSUE THREAD

**Issue by surchs** [neurobagel/api#114]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New feature

The current README instructions expect variables in the shell to be called `USERNAME` and `PASSWORD` for configuring the `docker compose` environment. That's not a good idea, because these shell variable names are likely to be already set by some other configuration, leading to the need to first unset them (as outlined as well in the readme).

For example, in the z-shell, `USERNAME` is set to `$USER` by default (see https://linux.die.net/man/1/zshparam).

A better solution would be to use variable names that are less likely to clash in this way (or find some other way to override the shell primacy for these variables), such as by appending a unique prefix `NB_`.

E.g.:

`NB_GRAPH_USERNAME` and `NB_GRAPH_PASSWORD`

Since the username and password may be graph-specific, having `GRAPH` in the variable name can help to further minimize confusion about the purpose of the credentials.

### Unclear documentation

When fixed, update the README as well as the corresponding warning in the documentation: https://www.neurobagel.org/documentation/start/#launch-the-api-and-graph-stack

### Other steps to implement
- to avoid having to change names across modules (incl. any tests) when an environment variable accessed from within the API is renamed, can transform these into `namedtuple` variables with "name" and "val" fields
- when env vars are updated, update API tests

**Comment by gdevenyi** [comment]
Suggest explicitly setting `NEUROBAGEL_*` prefixes

**Comment by alyssadai** [comment]
Updated the spec following @gdevenyi's suggestion
