### ISSUE TITLE
[ENHANCEMENT] Pick some reasonable default username for the DB communication

### ISSUE THREAD

**Issue by gdevenyi** [neurobagel/api#119]
DBUser or such

Make sure stardog and graph db use the same name
See also https://github.com/neurobagel/documentation/issues/74

**Comment by surchs** [comment]
We have that here: https://github.com/neurobagel/documentation/wiki/Alternative-Graph-Backend-deployment.

Maybe as part of https://github.com/neurobagel/documentation/issues/74 we can bring that to both deployment docs
