### ISSUE TITLE
[DOCS] Clarify in the README what is part of the API vs part of graph setup

### ISSUE THREAD

**Issue by gdevenyi** [neurobagel/api#121]
This project uses the word API to denote a piece of server software, rather than the classic definition of an application programming interface. This leads to confusion.

Consider the existing issue titles, are they referring to bugs/enhancements of the endpoints the API provides, or the server software?

edit: 
https://neurobagel.org/infrastructure/ is a bit out of sync with the README, and we should make sure that we use consistent phraseology for API inside the README because we also discuss setting up the graph here.

- [x] parse the README
- [x] check for any mentions of API that are not referring to our own stuff
- [x] clarify graph mentions
- [x] reduce duplication with the official docs by linking to the official docs
- [x] close

**Comment by surchs** [comment]
main point here is to check if this is done or list the tasks that remain to close this

**Comment by surchs** [comment]
Checked the README and official docs. Clarified one instance of discussing endpoints (see PR). Once that goes in, this can be closes
