### ISSUE TITLE
Write a test for behaviour of `RETURN_AGG` option

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/api#126]
Currently, several of the tests in test_query.py use an aggregate query results object (`test_data()`) for testing.

We don't currently have a test that checks the structure of query results returned from the API depending on the set value of `RETURN_AGG`.

### Steps to implement
We could do one or both of
- ~testing the `create_query` function to check that the SPARQL query is wrapped with an aggregator statement when `RETURN_AGG=true`~
- mocking a small response from the graph (monkeypatching the `httpx` post function) to see if the graph results are parsed appropriately on the API side depending on `RETURN_AGG`

**Comment by surchs** [comment]
:rocket: Issue was released in [`v0.2.0`](https://github.com/neurobagel/api/releases/tag/v0.2.0) :rocket:
