### ISSUE TITLE
Update expected dataset-level attributes in query response model

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/api#129]
To stay aligned with bagel-cli [data model](https://github.com/neurobagel/bagel-cli/blob/main/bagel/models.py) updates...

- [x] remove `dataset_file_path` from results model & query template
- [x] remove "" from crud.py results processing
- [x] add unique dataset identifier (directly obtained from graph) back into results model
  - see commit https://github.com/neurobagel/api/commit/e7b71f3166e338a01ca3db97508d7f92d8734f43
- [x] update test examples
- [x] the dataset portal URI is currently optional (provided by user in a CLI arg) since not all datasets will have a dedicated website/page, but this is a required property in the query template + data model, e.g.
https://github.com/neurobagel/api/blob/aeee164525bfc80fb4dce3191e322d9e4ecd91a6/app/api/utility.py#L141-L146
  - to fix, wrap `dataset_portal_uri` in an optional statement + update `CohortQueryResponse` class

**Comment by rmanaem** [comment]
Related to https://github.com/neurobagel/query-tool/issues/120
