### ISSUE TITLE
Project Structure

### ISSUE THREAD

**Issue by rmanaem** [neurobagel/api#14]
.
└── bagelapi/
    ├── app/
    │   ├── __init__.py
    │   ├── main.py
    │   └── api/
    │       ├── __init__.py
    │       ├── routers/
    │       │   └── query.py
    │       ├── crud.py
    │       ├── models.py
    │       └── utility.py:constants.py + core.py
    └── tests/
        ├── __init__.py
        ├── conftest.py
        └── test_crud.py

[Tree structure tool instance](https://tree.nathanfriend.io/?s=(%27options!(%27fancy6~fullPath!false~trailingSlash6~rootDot6)~9(%279%27bagelapi5app*343main2api*0403routers*003queryAcrudAmodelsAutility7%3Aconstants7%20%2B%20core758s*4conf828_crud2%27)~version!%271%27)*500%20%2027*3-%204__init__25%5Cn06!true7.py8test9source!A203%01A987654320*)

**Comment by surchs** [comment]
@rmanaem new ping: can we close this :)

**Comment by rmanaem** [comment]
@surchs we planned on keeping this issue open and update it as we progress through the project

**Comment by alyssadai** [comment]
I think we're both familiar enough with the project structure now that we can close this. Thanks for the bump!
