### ISSUE TITLE
Add script to upload JSONLD to deployed graph

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/api#147]
- [x] Add line to delete any existing data in graph (maybe by removing triples?)
- [x] Modify script to have a configurable host + port number
- see also https://github.com/neurobagel/documentation/issues/52
- replaces https://github.com/neurobagel/bulk_annotations/issues/5

**Comment by surchs** [comment]
Just thinking out loud: our suggestion for a user who runs this will be:

- clone the API repo locally
- make changes to example .env file as needed
- from inside local repo, run docker compose up to make the stack come to life
- then, inside the local repo, run this nifty little shell script so your data appear in the new graph

Does that sound about right? 

Sidenote: git can make scripts start out as executable: https://git-scm.com/docs/git-add#Documentation/git-add.txt---chmod-x - might be useful.

**Comment by alyssadai** [comment]
@surchs yes that's what I have in mind! Cool tip about the executables
