### ISSUE TITLE
[BUG] nested variable substitution fails

### ISSUE THREAD

**Issue by thomasbeaudry** [neurobagel/api#170]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Expected Behavior

For the default docker-compose.yml file to work without any modifications

### Current Behavior

Nested variable substitution doesn't work for my version of Docker Compose version v2.2.3

So the original config:

    environment:
      API_QUERY_URL: "${API_QUERY_URL:-http://localhost:${NB_API_PORT_HOST:-8000}/}"

Needs to be:

    environment:
      API_QUERY_URL: "${API_QUERY_URL:-http://localhost:8000/}"

### Error message

invalid interpolation format for services.query.environment.API_QUERY_URL: "[http://localhost:${NB_API_PORT_HOST:-8000](http://localhost:%24%7Bnb_api_port_host:-8000/)". You may need to escape any $ with another $.

### Environment

- OS:
- Python/Node version:

**Comment by alyssadai** [comment]
This also currently fails on our Arbutus cloud server for Docker Compose version v.2.17.2.

See also https://github.com/docker/compose/pull/5268#issuecomment-1666792510
