### ISSUE TITLE
[BUG] Have to use `NB_GRAPH_PORT` instead of `NB_GRAPH_PORT_HOST`

### ISSUE THREAD

**Issue by surchs** [neurobagel/api#190]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Expected Behavior

At the moment, we're using `NB_GRAPH_PORT_HOST` to construct the Query URL. However the API is in a docker network with the graph and will therefore have to send requests to the graph on the graph's internal port `NB_GRAPH_PORT`. 

https://github.com/neurobagel/api/blob/2a6fc31bc4bc11ee767860d294fc076f7d9c2e73/app/api/utility.py#L26-L36

We have to change these lines and the corresponding docker-compose file so that we expose and use `NB_GRAPH_PORT` instead.

### Anything else?

We should also document in our internal docs that within a docker network services talk to each other on their internal port number, and not the one that is exposed to the host.

**Comment by alyssadai** [comment]
Note: This breaks down if the API that's running is not in the same Docker network as the graph, i.e. if you have locally spun up an API using Python. In this scenario, you need to specify the HOST port in the query URL, not the CONTAINER port.

**Comment by surchs** [comment]
for reference: 

![Image](https://github.com/neurobagel/api/assets/1302022/047b5a25-9d02-414e-91b3-6929f0bb3c87)

from https://docs.docker.com/network/drivers/bridge/#connect-a-container-to-a-user-defined-bridge

So in other words: within the same docker network, no action is required for the ports of container A to be visible to container B. That implicitly also means: no action can be taken so that port 1 on container A is mapped to a different port number for container B. 

See also 

![Image](https://github.com/neurobagel/api/assets/1302022/ecf8075f-e085-4288-8d50-4e20a00018cf)

from https://docs.docker.com/network/

This is different from how we expose ports from individual containers to the host using the --publish flag. There we can map a container port to a different port number on the host.
