### ISSUE TITLE
Change root path for API to display an informative landing message/page

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/api#199]
Currently, navigating to the root of the API (`/`) displays a `{"detail": "not found"}` message by default.

We want to update our path config in FastAPI to instead show a page that displays a simple welcome message and directs users to visit the API docs for more information should be sufficient, e.g.:

> Welcome to the Neurobagel REST API!
>
> Please visit the documentation at /docs to view available API endpoints.

(If `/docs` part could be made a link to the `<base-url>/docs`, that would also be cool but is not a necessity.)

**Comment by samadpls** [comment]
Hi @alyssadai , can i work on this task too :)

**Comment by surchs** [comment]
:rocket: Issue was released in [`v0.2.0`](https://github.com/neurobagel/api/releases/tag/v0.2.0) :rocket:
