### ISSUE TITLE
Update vocabulary path to parse and return `nb:Diagnosis` options

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/api#211]
Add workflow for the path `/attributes/nb:Diagnosis/vocab` that:
- [x] Reads in a file of SNOMED diagnosis term-label mappings (downloaded from Athena) on startup + creates a lookup file
  - a copy should probably be stored in the repo for now, under https://github.com/neurobagel/api/tree/main/vocab/backup_external
  - The diagnosis term-label mappings can be found here https://github.com/neurobagel/annotation_tool/blob/main/static/diagnosisTerms.json
- [x] Processes the mappings into a `VocabLabelsResponse` object
- [x] append the missing terms (see below) to the SNOMED-CT .json dump
  - already done in .json used by annotation tool
- [x] update the code snippet in https://github.com/neurobagel/planning/issues/52 to also include the appended terms that are missing, so it is re-executable
- ~Allows only password-authenticated users to access that endpoint~

Other TODO:
- [x] wrap requests to external vocab APIs in a `try-except` for httpx network errors (currently, if the network connection cannot be established if, e.g. the internet is down, an exception is raised and the app cannot start)
  - [x] if catch is hit, raise informative warning and use local copy of vocab file

**Comment by surchs** [comment]
do we have a list of diagnoses that we would need for OpenNeuro but that aren't in our SNOMED-CT dump?

**Comment by rmanaem** [comment]
6 terms that are present in the `open_neuro` but not in this newly curated list:

| BioPortal id   |      Label   |
|----------|:-------------:|
| 432119003 | Aneurysm |
| 87486003 | Aphasia |
| 59770006 |    Dyslexia |
| 203082005 |  Fibromyalgia |
| 238131007 | Overweight |
| 397540003 | Visual impairment |
