### ISSUE TITLE
Query response should include total number of subjects in a dataset

### ISSUE THREAD

**Issue by surchs** [neurobagel/api#216]
The query response should include the total number of unique subjects in a dataset so that the user knows what subset their query has matched. This will also help us make our sample-level search more easy to visualize on the graphical query tool

- [x] dataset level response object has a key for `total_number_subjects` or similar with a `int` value equal to # of subjects in dataset
- [x] add logic for a separate query to graph for total # subjects in matching datasets

**Comment by surchs** [comment]
@neurobagel/dev anything else to be done than the checkbox in the spec?

**Comment by alyssadai** [comment]
Blocked by #202 for dev experience reasons
