### ISSUE TITLE
Warn about quotes interpretation in README instructions for using API docker image directly

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/api#224]
In the below sections of the README, we should explicitly instruct users to not wrap any space-separated values for variables in the .env file in quotation marks:
- [x] https://github.com/neurobagel/api#option-2-use-the-latest-image-from-docker-hub
- [x] https://github.com/neurobagel/api#option-3-build-the-image-using-the-dockerfile
(for now, it's probably just the `NB_API_ALLOWED_ORIGINS` variable that this applies to)

See our internal wiki https://github.com/neurobagel/documentation/wiki/Docker#docker-cli-docker-run for why the quotes are a problem

Originally posted by @surchs in https://github.com/neurobagel/federation-api/pull/22#pullrequestreview-1732149368

**Comment by samadpls** [comment]
Hi @alyssadai, I have created a PR #284  related to this ticket. Could you please review it when it's convenient for you? 
Thanks so much!

**Comment by surchs** [comment]
:rocket: Issue was released in [`v0.2.0`](https://github.com/neurobagel/api/releases/tag/v0.2.0) :rocket:
