### ISSUE TITLE
Update query template to make session optional

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/api#225]
Datasets with imaging data that cannot be modeled by the CLI end up with JSONLDs in which subjects have no (imaging) session info. Since the query template used in the API assumes that all subjects have at least one session (see https://github.com/neurobagel/api/blob/18d5d95ecf8ae6c2ee4b56cbe7a279ef684a8498/app/api/utility.py#L185-L188), these datasets are never matched by any query sent using the API/query tool (e.g., this happens for 7/340 datasets in the `open_neuro` graph).

TODO:
- [ ] Update the API query template to match subjects without any imaging sessions (i.e., those with only phenotypic data)
- [ ] As part of this issue or soon after, probably move our data model limitations page to the official docs
  - [ ] and describe what happens when you are querying for # sessions

- See also https://github.com/neurobagel/planning/issues/54

**Comment by surchs** [comment]
One oddity that will hopefully be fixed by this issue is that a completely empty query for PPMI currently shows only a subset of the PPMI subjects we know about:

![Image](https://github.com/neurobagel/api/assets/1302022/8fb4b19b-2ffc-484a-acf6-c8553faffac8)
