### ISSUE TITLE
Add flag for `add_data_to_graph.sh` to write output to a log file

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/api#250]
If you want to be able to check the detailed HTTP response for files that failed the upload (summarized at end of script output), currently you either have to scroll up in your terminal through the whole script STOUT, or make sure to direct the output of `add_data_to_graph.sh` to a file as you're running it.

Having a flag for the script to write all output to a LOG.txt or similar file could be very useful to simplify debugging.

**Comment by samadpls** [comment]
Hi @alyssadai, it seems like a great start with this issue. Could you please assign it to me? :)

**Comment by alyssadai** [comment]
Hi @samadpls, thanks a lot for your interest!

If you'd like to work on this issue, we welcome you to open a PR directly when you're ready! (We currently only assign issues as a way to internally track what is being actively worked by maintainers). You can assign me or one of the other [maintainers](https://neurobagel.org/contributing/team/) to review the PR.
