### ISSUE TITLE
Refactor mock get method for testing to accept return object

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/api#266]
We keep using a `mocked_get()` function pretty much everywhere. A variant of this has already been refactored into the `conftest.py` file, so it probably makes sense to just have a single mock method but have it accept the return type as an argument. Something like so:

```python
def my_mock_get(expectedReturn):
  async def inner_mock(some, other, args):
    return expectedReturn
  return inner_mock
```

It seems that you can do something like this with fixtures in pytest using indirect parameterizations: https://docs.pytest.org/en/latest/example/parametrize.html#apply-indirect-on-particular-arguments

_Originally posted by @surchs in https://github.com/neurobagel/api/pull/264#discussion_r1462460857_

**Comment by surchs** [comment]
:rocket: Issue was released in [`v0.2.0`](https://github.com/neurobagel/api/releases/tag/v0.2.0) :rocket:
