### ISSUE TITLE
Update `num_{imaging,phenotypic}_sessions` to be `num_matching_{imaging,phenotypic}_sessions`

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/api#271]
The query result for a given subject currently looks like this:
```bash
      {
        "sub_id": "sub-03",
        "session_id": "ses-02",
        "num_phenotypic_sessions": 1,
        "num_imaging_sessions": 2,
        "session_type": "http://neurobagel.org/vocab/PhenotypicSession",
        "age": 23.2,
        "sex": null,
        "diagnosis": [
          "http://purl.bioontology.org/ontology/SNOMEDCT/406506008"
        ],
        "subject_group": null,
        "assessment": [
          "https://www.cognitiveatlas.org/task/id/trm_57964b8a66aed",
          "https://www.cognitiveatlas.org/task/id/tsk_4a57abb949ece"
        ],
        "image_modal": [
          null
        ],
        "session_file_path": null
      },
```
However, the number of phenoypic and imaging sessions are not actually the total # sessions, but the sessions matching the query. We should clarify this in the result to avoid confusion.

### Steps to implement
- [x] Update the query response model
- [x] Update the default query file
- [x] Update the query template

**Comment by surchs** [comment]
:rocket: Issue was released in [`v0.2.0`](https://github.com/neurobagel/api/releases/tag/v0.2.0) :rocket:
