### ISSUE TITLE
Default httpx timeout too short

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/api#304]
Our current default timeout limit of 30s is now too short of a window for the n-API to receive the response data from graph, now that we have upgraded to a session-level graph data model (meaning the # triples has greatly increased).

Until we do some internal optimization, we should disable this timeout to avoid n-APIs always timing out for large graph stores.
https://github.com/neurobagel/api/blob/1f89c22bc37e462261c845cf975c90707681f3c7/app/api/crud.py#L22-L50

**Comment by surchs** [comment]
:rocket: Issue was released in [`v0.2.1`](https://github.com/neurobagel/api/releases/tag/v0.2.1) :rocket:
