### ISSUE TITLE
Endpoint that will return the list of available termURLs for a given query parameter

### ISSUE THREAD

**Issue by surchs** [neurobagel/api#37]
There should be an API endpoint or resource where I can request a list of all of the termURLs that are currently available for a given variable in the graph, so that I know what makes sense to query.

e.g. I want to get all of the unique `diagnosis` terms that exist in the current graph returned as an array.

~There might also be a way to just get this for all of the categorical variables: e.g. a single endpoint that returns an object with the existing terms for all variables:~ (EDIT: we will not implement this as one endpoint - instead we will have a separate endpoint that returns all the variables with controlled term instances. See also #176)
```json
{
"diagnosis": ["snomed:1", "snomed:2", ...],
"imagingModality": ["T1", "T2", ...],
...
}
```

### Steps to implement
- [x] Create a `GET` path operation with the controlled term of the Neurobagel class (e.g., `nb:Assessment`?) as a [path parameter](https://fastapi.tiangolo.com/tutorial/path-params/)
  - `api.neurobagel.org/attributes/{attribute_URI}`
  - e.g. route for getting all the TermURLs for Diagnosis would be `api.neurobagel.org/attributes/nb:Diagnosis`
    - note: having colons in the path param _should_ be fine, see https://github.com/encode/starlette/discussions/1673
- [x] corresponding crud function will post a query to the graph endpoint to return all instances of that class
- [x] Response should be in the format of:
`{attribute_URI: [termURL1, termURL2, termURL3…]}`

References for inspo:
- https://www.cognitiveatlas.org/api
- GraphDB [retrieving namespaces](https://rdf4j.org/documentation/reference/rest-api/#tag/Repositories/paths/~1repositories/get) vs [getting a namespace by prefix](https://rdf4j.org/documentation/reference/rest-api/#tag/Namespaces/paths/~1repositories~1%7BrepositoryID%7D~1namespaces~1%7BnamespacesPrefix%7D/get)

**Comment by rmanaem** [comment]
@alyssadai Mind if I take this?

**Comment by rmanaem** [comment]
PP it is then!

**Comment by surchs** [comment]
I'm putting this into "Ready", I think it has enough detail.

**Comment by surchs** [comment]
Bumping this to roadmap, not part of current focus

**Comment by alyssadai** [comment]
@surchs @rmanaem, can you take a look and let me know if the `Steps to implement` makes sense to you / if anything's missing?

**Comment by alyssadai** [comment]
@surchs & @rmanaem, I've updated the spec with what I think is the simplest predictable endpoint for this purpose. Let me know if you agree or if anything else needs to be further fleshed out.

**Comment by rmanaem** [comment]
I recall we discussed not restricting the user input for the `attribute_URI` query parameter but given a simple SPARQL query like 
```
SELECT DISTINCT ?termURL
WHERE {
        ?termURL a {attribute_URI}.
    }
```
used to retrieve term URLs, a user can query the term URL for any class. Are we ok with that?

**Comment by surchs** [comment]
very good question! In https://github.com/neurobagel/api/issues/176 we discussed having something special about "our classes" so we can find them easily for the "what classes do you have?" endpoint. I think it would make sense to use the same logic here to prefilter the list of classes you can ask about. wdyt?

**Comment by rmanaem** [comment]
I think that's a good idea.
