### ISSUE TITLE
Revisit how queries for 'healthy controls' should be handled relative to the diagnosis param

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/api#43]
Currently `diagnosis` and `is_control` are separate query parameters, and there is a constraint that users cannot search for a non-default diagnosis and `is_control=True` simultaneously.

The URI for control subject comes from NCIT (since SNOMED does not have a suitable equivalent), http://purl.obolibrary.org/obo/NCIT_C94342.

Some decisions to be discussed further are:

- Will annotations of subjects with both a diagnosis and a status of healthy control be allowed in the graph in the first place?
- Will/could a URI for healthy control also be allowed to exist as a value for `diagnosis`? (This is the currently true in the tester graph, but is ignored in the current implementation of the API) i.e., if users have a "diagnosis" column in their csv that differentiates patients and controls, what would this map to in the graph during annotation?
- If a subject queries only for `is_control=True`, who should this return? Only healthy controls from datasets that also had patients? Or subjects from datasets that didn't have diagnosis info as well?
- How would a subject in a dataset that doesn't have any diagnosis info be annotated?

**One option:** In a dataset with both patients and controls, for `diagnosis`, patients could be annotated with their disease IRI while controls don't have any annotation (so basically, there would be no info about controls in the `diagnosis` variable), and there could be another relation called `bg:isSubjectGroup` with URIs (maybe from NCIT) for e.g. healthy control, patient, and general subject such that each of the patients/controls are also associated with a subject group

**Comment by surchs** [comment]
@alyssadai: I think this thing needs revisiting. Two options I see: 1) close because we didn't work on it for more than half a year, wait for it to come up again. 2) keep open, add to some bigger "tricky modeling questions" roadmap issue, and then remove from the project.

Thoughts?

**Comment by alyssadai** [comment]
@surchs I think this specific issue is okay to close actually, since we ended up (subconsciously? 🤣) implementing the suggested option of generalizing what was formerly the `is_control` variable to `isSubjectGroup`, which I think confers the flexibility that will be useful in future if we want to support other not-strictly-healthy-control-nor-patient types of subjects. At least, I think this is what I was thinking while writing the issue!
