### ISSUE TITLE
Add bg:isSubjectGroup to SPARQL query pattern in create_query function

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/api#44]
The SPARQL query template currently doesn't include a triple pattern for `bg:isSubjectGroup` (although a filter using the variable name `subject_group` is added when `is_control=True`) as this relation does not currently exist in the graph.

Once subject group has been added to the neurobagel datamodel, update the query template as follows in utility.py:

```
...
?subject a bg:Subject;
            bg:label ?sub_id;
            bg:age ?age;
            bg:sex ?sex;
            bg:diagnosis ?diagnosis;
            bg:isSubjectGroup ?subject_group;
            bg:hasSession/bg:hasAcquisition/bg:hasContrastType ?image_modal.
...
```

**Comment by surchs** [comment]
Hey @alyssadai and @rmanaem. The test graph has the expected `isSubjectGroup` triples now for subjects who are healthy controls. I.e.:

```sparql
PREFIX bg: <http://neurobagel.org/vocab/>
PREFIX snomed: <http://neurobagel.org/snomed/>
PREFIX nidm: <http://purl.org/nidash/nidm#>

SELECT DISTINCT ?subject ?subject_group ?diagnosis
WHERE {
    ?subject a bg:Subject;
            bg:label ?sub_id;
            bg:age ?age;
            bg:sex ?sex;
            bg:diagnosis ?diagnosis;
            bg:isSubjectGroup ?subject_group.
}
```

returns a number of reasonable looking results. LMK if this is resolved
