### ISSUE TITLE
Discuss test assertions

### ISSUE THREAD

**Issue by rmanaem** [neurobagel/api#60]
Asserting over what is returned from the mocked `get` function in `test_query` has been brought up multiple times during conversations and PRs, most recently [here](https://github.com/neurobagel/bagelapi/pull/55#discussion_r1068536437).
I'd like us to think about the questions below:
- Is what we have unnecessary? since it's simply being fed into the test and asserted on
If not
- Is what we currently have (simply check if the returned list is empty or not) enough?
If not
- Do we want to check each of the properties in the `AggDatasetResponse`?

Or perhaps we need to re-think and re-work the implementation.

Other thoughts related to testing:

Because we are mocking [our `get` method](https://github.com/neurobagel/bagelapi/blob/cdaba2be5b17cd0e6e811e3be663a525b907f2a1/app/api/crud.py#L42) in our tests (good), and the query generator is called only inside the `get` method - technically inside the `httpx.post` call (neutral), the query generator is never tested (bad).

One answer is to make separate unit tests for the query generator.

What do you think?

**Comment by surchs** [comment]
Related to #48

**Comment by surchs** [comment]
I would say we make this issue more concrete and make a list of explicit tests we want to add here. What I can see in the description:

- Test that the query generated by the query generator makes sense / meets expectations / works
- Make more of an integration / e2e test where we test that the request we send to a graph is in fact understood

**Comment by alyssadai** [comment]
Closing in favour of https://github.com/neurobagel/api/issues/283
