### ISSUE TITLE
Modifying how aggregate image modality info is presented in query response

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/api#63]
I like having the info about the represented image modalities per dataset, but I think it could be a bit clearer either on the API side or whenever you implement it on the frontend side. For instance, right now a value of
```
"image_modals": ["http://purl.org/nidash/nidm#T1Weighted", "http://purl.org/nidash/nidm#T2Weighted"]
```
for a no-filters query means that at least one subject in each returned dataset has images of each listed modality. I think this output becomes unintuitive to interpret for datasets where not everyone has the same modalities available (e.g., if 100/100 subjects have T1 images, but only 50/100 have T2 images), or for queries where you're filtering by a certain modality. e.g., If a user is just looking for subjects with T1 data, the resulting `image_modals` could still be the same as the above which means that all subjects returned have T1 data, and _at least one_ of those subjects also has T2 data. But I'm not sure this would be immediately clear from the `image_modals` list itself.

I realize that currently the test data provides only datasets where everyone has the same modalities acquired, so this could definitely be a discussion point to revisit.

Some ideas to make this output more intuitive:
- Could we combine the aggregate image modality info with the number of matching subjects? To show the _# subjects per modality_ for a given query.
- We could just document clearly how to interpret the `image_modals` list (i.e., what multiple modalities means when you queried for only one, or the fact that it doesn't necessarily apply to all matching subjects), either in the frontend or in user-facing documentation.

What do you think?

_Originally posted by @alyssadai in https://github.com/neurobagel/bagelapi/pull/61#discussion_r1084357507_

**Comment by surchs** [comment]
@alyssadai I believe this has been addressed in the API. Can you confirm and close?

**Comment by alyssadai** [comment]
@surchs I believe our latest changes to the outputs of the query tool address this (i.e., having a `"AvailableImageModalities"` column in the dataset-level csv and a list of `"Modality"` column in the participant-level csv). I do think this info in the json returned from the API itself could be a little bit clearer in naming or docs, e.g., the `image_modals` attribute for datasets should probably be `available_image_modals`, but it's probably not a priority right now since / something we can revisit based on user feedback.

Does that make sense?

**Comment by surchs** [comment]
Yeah, this makes sense to me. Do you have a good idea what to do about these kinds of things like "we have a sense that a user might want this later but we won't do it now"? I'd like to keep issues from going stale, but it also doesn't feel right to just close it all. Maybe use "discussions" after all? Or something else where users can vote for features?

**Comment by alyssadai** [comment]
Haven't used Discussions before so I can't speak to how smoothly it'd integrate into our workflow, but I'm open to trying it if the team likes the idea! 

One caveat is I think it's probably much less visible to a normal user than the repo issues (if the plan is to close these types of issues) - based on what I've seen on other tools, it seems generally people just upvote features that haven't been addressed yet but they want 😛 

I know issue label management is still something we need to sort out a little bit, but what about like a `nice-to-have` label or something that at least separates it from "necessary" features?

**Comment by surchs** [comment]
ok, let's discuss on Thursday. But I think we can make issues work as long-term feature request collectors as well!
