### ISSUE TITLE
Turn the regex used for validation in models.py to a constant

### ISSUE THREAD

**Issue by rmanaem** [neurobagel/api#64]
Turn the regex below into a reusable constant for "a SPARQL variable from a controlled namespace"
https://github.com/neurobagel/api/blob/fc48a2c2b53bd1907b9825505024a93b9f6ec4f3/app/api/models.py#L19

**Comment by alyssadai** [comment]
@rmanaem I think this is a fairly straightforward refactoring that can probably be addressed for this release, so I've moved it to the Backlog on the Kanban board. :) Feel free to reshuffle the priority as you see fit!
