### ISSUE TITLE
Implement check for requests sent from a non McGill-IP address

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/api#70]
For local/dev launches of the API, the docs can be reached but queries from a non-McGill network IP (e.g., if you're not connected to the VPN) will result in an internal server error (`httpx.ConnectTimeout` behind the scenes). To make this more transparent, we could potentially add an initial [check for the client's IP address](https://fastapi.tiangolo.com/advanced/using-request-directly/#details-about-the-request-object) and provide an informative error if it's not within the McGill IP blocks we've granted access to on OpenStack.

**Comment by alyssadai** [comment]
@surchs what do you think? One thing I'm not sure about that this solution will do is expose the permitted IP ranges in the codebase...I guess in theory an advanced user would know how to look for them anyways since they're public. Wondering if this is worth catching as I think it only really applies to the local Python deployment.

**Comment by surchs** [comment]
I think exposing the IPs is OK, but I'd be concerned that we now couple the error handling to our specific deployment. Is there a more generic way of catching the "the graph api doesn't talk to me because I don't make it past the firewall" error?
