### ISSUE TITLE
Fix Certbot certificate auto-renewal

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/api#73]
Auto-renewal of the `api.neurobagel.org` HTTPS certificate is currently set up for Certbot, but it will not work given the new OpenStack firewall (which only grants server access to the McGill network). One option would be to manually disable the firewall and renew the certificate as needed, but it would be worth looking into options for allowing Certbot through the firewall automatically.

EDIT: Based on [this post](https://community.letsencrypt.org/t/certbot-request-open-firewall-only-for-specific-ips/121656/7) in the CertBot community, it looks like there isn't an easy way to do this at the OpenStack firewall level.

For now, we can instead:
- [x] Create a new security group for CertBot that allows all traffic to ports 80/443 (which is needed for "challenge" requests to go through during the renewal, see https://letsencrypt.org/docs/challenge-types/#http-01-challenge). This security group can be briefly added to our cloud instance for renewals

**Comment by alyssadai** [comment]
Bumping up importance as current certificate expires April 30.

**Comment by surchs** [comment]
Awesome, thanks for addressing this @alyssadai. What remains to be done for this to be closed?

**Comment by alyssadai** [comment]
It can be closed! 🙂
