### ISSUE TITLE
Make a first release

### ISSUE THREAD

**Issue by rmanaem** [neurobagel/api#76]
We need to release the API so it can be cited in a grant. 

Steps:

- [x] Pick a semver version (see below discussion, if in doubt, let's go with 0.1.0)
- [x] Follow [these descriptions](https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content) so Zenodo can mint a DOI for our release of the API
  - @Remi-Gau please edit sub-points for things not in that doc
- [x] add a citation.cff files + validation workflow with basic metadata
  - see: https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md
- [x] enable tracking of the repository by Zenodo **before** making a release
- [x] make a release on github (see https://github.com/neurobagel/documentation/wiki/Release-process)
  - stick to basic description of features
- [x] confirm that a DOI has been minted and dereferences to our codebase, and then share it with @Remi-Gau so he can put it in a grant that makes everybody happy :money_with_wings:

**Comment by surchs** [comment]
Up to you, but I think for v0.1 the swagger docs + README for deployment are sufficient

**Comment by rmanaem** [comment]
I guess we can move it to V0.2 and update this issue's description as we make our way through issues

**Comment by rmanaem** [comment]
what do u think @alyssadai ?

**Comment by alyssadai** [comment]
Sounds good - done :) @rmanaem feel free to add any of the other open issues to 0.2.0 if it makes sense

**Comment by alyssadai** [comment]
For reviewer, here is the draft of the release notes: https://github.com/neurobagel/api/releases/tag/untagged-b968b2f0eebd04365cee

**Comment by surchs** [comment]
Looked over the release notes, good to go @alyssadai :cook: 

:tada:

**Comment by alyssadai** [comment]
Closing as this is resolved - not sure why I apparently moved it to "Review - Done" while it was still open 🤔
