### ISSUE TITLE
bump isort pre-commit to v15.12.x

### ISSUE THREAD

**Issue by surchs** [neurobagel/api#80]
As described in this stackoverflow post: https://stackoverflow.com/questions/75269700/pre-commit-fails-to-install-isort-5-11-4-with-error-runtimeerror-the-poetry-co there is a problem with isort < v15.12 having an unpinned dependency on poetry and being incompatible with the most recent poetry version. if you run pre-commit with the pinned isort version (https://github.com/neurobagel/api/blob/main/.pre-commit-config.yaml#L26) on a new/updated environment, the pre-commit will crash.

Simple fix is to pin v15.12.0 for isort in the pre-commit yaml file

**Comment by alyssadai** [comment]
Thanks for catching this!
